Tugas-7-Template/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CastController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layouts/beranda');
});

Route::view('table', 'table');
Route::view('data-tables', 'data-tables');

Route::resource('cast', CastController::class);

Tugas-7-Template/app/Models/Cast.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cast extends Model
{
    use HasFactory;
    protected $fillable = [
        'nama',
        'bio',
        'umur',

];

protected $guarded = ['id'];
}

Tugas-7-Template/app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

Tugas-7-Template/app/Http/Controllers/CastController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cast;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class CastController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cast = DB::table('casts')->get();
        return view('cast', compact('cast'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $cast = DB::table('casts')->get();
        return view('cast-add', compact('cast'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = $request->validate([
            'nama'=> 'required',
            'umur'=> 'required',
            'bio'=> 'required',

            ]);

            $cast = DB::table('casts')->insert([
                "nama" => $request["nama"],
                "umur" => $request["umur"],
                "bio" => $request["bio"]
            ]);
            return redirect('cast');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Cast  $cast
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $cast = Cast::findOrFail($id);
        return view('cast-show', compact('cast'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Cast  $cast
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cast = DB::table('casts')->where('id', $id)->first();
        return view('cast-edit', compact('cast'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Cast  $cast
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $cast = Cast::findOrFail($id);
        $validator = $request->validate([
            'nama'=> 'required',
            'umur'=> 'required',
            'bio'=> 'required',

        ]);

        $cast = DB::table('casts')
        ->where('id', $id)
        ->update([
            'nama' => $request["nama"],
            'umur' => $request["umur"],
            'bio' => $request["bio"]
        ]);
        return redirect('cast');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Cast  $cast
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cast = DB::table('casts')->where('id', $id)->delete();;
        return redirect('cast');
    }
}

Tugas-7-Template/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

Tugas-7-Template/resources/views/cast-add.blade.php
@extends('layouts.template')

@section('title', 'Tambah Data Cast')

@section('content')
    <div class="card card-primary">
        <div class="card-header">
            <h3 class="card-title">Tambah Data Cast</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form action="{{ route('cast.store') }}" method="POST">
            @csrf
            <div class="card-body">
                <div class="form-group">
                    <label for="exampleInputEmail1">Nama</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" name="nama" placeholder="Masukkan Nama">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Umur</label>
                    <input type="number" class="form-control" id="exampleInputPassword1" name="umur" placeholder="Masukkan Umur">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Bio</label>
                    <input type="text" class="form-control" id="exampleInputPassword1" name="bio" placeholder="Masukkan Bio">
                </div>

            </div>
            <!-- /.card-body -->

            <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>
    </div>
@endsection

Tugas-7-Template/resources/views/cast-edit.blade.php
@extends('layouts.template')

@section('title', 'Edit Data Cast')

@section('content')
<div class="card card-primary">
    <div class="card-header">
        <h3 class="card-title">Tambah Data Cast</h3>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
    <form action="{{ route('cast.update', $cast->id) }}" method="POST">
        @csrf
        @method('PUT')
        <div class="card-body">
            <div class="form-group">
                <label for="exampleInputEmail1">Nama</label>
                <input type="text" class="form-control" id="exampleInputEmail1" value="{{ $cast->nama }}" name="nama" placeholder="Masukkan Nama">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Umur</label>
                <input type="number" class="form-control" id="exampleInputPassword1" value="{{ $cast->umur }}" name="umur" placeholder="Masukkan Umur">
            </div>
            <div class="form-group">
                <label for="exampleInputPassword1">Bio</label>
                <input type="text" class="form-control" id="exampleInputPassword1" value="{{ $cast->bio }}" name="bio" placeholder="Masukkan Bio">
            </div>

        </div>
        <!-- /.card-body -->

        <div class="card-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
</div>
@endsection

Tugas-7-Template/resources/views/cast-show.blade.php
@extends('layouts.template')

@section('title', 'Detail Data Cast')

@section('content')
<div class="card">
    <div class="card-header">
        <h3 class="card-title">Detail Data Cast</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Detail</th>
                    <th>Isi Data</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Nama Cast</td>
                    <td>{{ $cast->nama}}</td>
                </tr>
                <tr>
                    <td>Umur Cast</td>
                    <td>{{ $cast->umur }}</td>
                </tr>
                <tr>
                    <td>Bio</td>
                    <td>{{ $cast->bio }}</td>
                </tr>
            </tbody>
        </table>
    </div>
@endsection

Tugas-7-Template/resources/views/cast.blade.php
@extends('layouts.template')

@section('title', 'Cast')

@section('content')

<div class="card">
    <div class="card-header">
        <h3 class="card-title">Data Cast</h3>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <a href="{{ route('cast.create') }}" class="btn btn-primary mb-3">Tambah Data</a>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th >#</th>
                    <th>Nama</th>
                    <th>Umur</th>
                    <th>Bio</th>
                    <th>Aksi</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($cast as $item)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $item->nama }}</td>
                    <td>{{ $item->umur }}</td>
                    <td>{{ $item->bio }}</td>
                    <td class="d-flex">
                        <a href="{{ route('cast.edit', $item->id) }}" class="btn btn-primary">Edit</a>
                        <a href="{{ route('cast.show', $item->id) }}" class="btn btn-warning ml-2">Detail</a>
                        <form action="{{ route('cast.destroy', $item->id) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger ml-2" type="submit" >Delete</button>
                        </form>
                    </td>
                </tr>

                @endforeach
            </tbody>
        </table>
    </div>

@endsection

Tugas-7-Template/resources/views/table.blade.php
@extends('layouts.template')

@section('title', 'Table')

@section('content')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Tables</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th style="width: 10px">#</th>
                        <th>Task</th>
                        <th>Progress</th>
                        <th style="width: 40px">Label</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1.</td>
                        <td>Update software</td>
                        <td>
                            <div class="progress progress-xs">
                                <div class="progress-bar progress-bar-danger" style="width: 55%"></div>
                            </div>
                        </td>
                        <td><span class="badge bg-danger">55%</span></td>
                    </tr>
                    <tr>
                        <td>2.</td>
                        <td>Clean database</td>
                        <td>
                            <div class="progress progress-xs">
                                <div class="progress-bar bg-warning" style="width: 70%"></div>
                            </div>
                        </td>
                        <td><span class="badge bg-warning">70%</span></td>
                    </tr>
                    <tr>
                        <td>3.</td>
                        <td>Cron job running</td>
                        <td>
                            <div class="progress progress-xs progress-striped active">
                                <div class="progress-bar bg-primary" style="width: 30%"></div>
                            </div>
                        </td>
                        <td><span class="badge bg-primary">30%</span></td>
                    </tr>
                    <tr>
                        <td>4.</td>
                        <td>Fix and squish bugs</td>
                        <td>
                            <div class="progress progress-xs progress-striped active">
                                <div class="progress-bar bg-success" style="width: 90%"></div>
                            </div>
                        </td>
                        <td><span class="badge bg-success">90%</span></td>
                    </tr>
                </tbody>
            </table>
        </div>
        @endsection